/** @type {import('tailwindcss').Config} */
module.exports = {
  important: '.innerbody',
  content: [
    "./layouts/**/*.html",
    "./content/**/*.{html,md}",
    "./themes/**/layouts/**/*.html",
    "./static/js/**/*.{js,jsx}",
  ],
  plugins: [require("daisyui")],
  theme: {
    extend: {},
  },
  daisyui: {
    themes: ["light", "dark"],
    logs: false,
  },
  safelist: [
    'btn',
    'btn-primary',
    'btn-secondary',
    'btn-accent',
    'btn-info',
    'btn-success',
    'btn-warning',
    'btn-error',
    'menu',
    'modal',
    'card',
    'indicator',
    'badge',
    'alert',
    'artboard',
    'avatar',
    'checkbox',
    'collapse',
    'dropdown',
    'footer',
    'form-control',
    'input',
    'join',
    'label',
    'progress',
    'radial-progress',
    'select',
    'swap',
    'table',
    'toast',
    'toggle',
    'tooltip'
  ]
} 