'use strict';

/**
 * This function helps CloudFront properly serve index.html files for directory paths
 * which is critical for static sites generated by Hugo.
 *
 * For example:
 * - /volunteer/ will serve /volunteer/index.html
 * - /volunteer (without trailing slash) will redirect to /volunteer/
 * - /events/my-event/ will serve /events/my-event/index.html
 * - /events/my-event (without trailing slash) will redirect to /events/my-event/
 */
function handler(event) {
    var request = event.request;
    var uri = request.uri;
    
    // If URI doesn't end with a slash and doesn't have a file extension
    if (!uri.endsWith('/') && !uri.includes('.')) {
        // Redirect to the same path with trailing slash
        return {
            statusCode: 301,
            statusDescription: 'Moved Permanently',
            headers: {
                'location': { value: uri + '/' }
            }
        };
    }
    
    // If URI ends with a slash, append 'index.html'
    if (uri.endsWith('/') && !uri.endsWith('/index.html')) {
        request.uri = uri + 'index.html';
    }
    
    return request;
}
