
import type { Product } from '../types';

// This file was generated by scripts/sync-products.js
// Last updated: 2025-09-12T03:07:25.931Z
export const products: Product[] = [
  {
    id: 'prod_T1FEbGaQbHYlEl',
    name: 'Upcycled T-Shirt - Large',
    price: 30,
    currency: 'USD',
    stripePriceId: 'price_1S5Cjt3IH8C7AKmurg5DAnls',
    description: '',
    images: [
      'https://files.stripe.com/links/MDB8YWNjdF8xUzVCdkkzSUg4QzdBS211fGZsX3Rlc3RfaVR6amY0dzg1RVI0djNxWEtnd3NRSEt600Q0jbW0Os'
    ]
  }
];
